export const games = [
  {
    id: "cyberpunk-2077",
    title: "Cyberpunk 2077",
    genre: "RPG / Acción",
    price: 599,
    originalPrice: 999,
    rating: 4.7,
    reviews: 48200,
    image: "🌆",
    gradient: "from-yellow-500 to-pink-600",
    tag: "OFERTA",
    description: "Un RPG de mundo abierto ambientado en Night City, una megalópolis obsesionada con el poder y el glamour.",
    platform: ["PC", "PS5", "Xbox"],
  },
  {
    id: "elden-ring",
    title: "Elden Ring",
    genre: "Souls / Acción",
    price: 799,
    originalPrice: null,
    rating: 4.9,
    reviews: 62100,
    image: "⚔️",
    gradient: "from-amber-600 to-orange-800",
    tag: "BEST SELLER",
    description: "Forja tu leyenda en las Tierras Intermedias. Un mundo abierto épico creado junto a George R.R. Martin.",
    platform: ["PC", "PS5", "Xbox"],
  },
  {
    id: "baldurs-gate-3",
    title: "Baldur's Gate 3",
    genre: "RPG / Estrategia",
    price: 849,
    originalPrice: null,
    rating: 4.9,
    reviews: 39800,
    image: "🧙",
    gradient: "from-purple-600 to-indigo-800",
    tag: "GOTY 2023",
    description: "Reúne a tu grupo y regresa a los Reinos Olvidados en una historia de amistad, traición y poder.",
    platform: ["PC", "PS5"],
  },
  {
    id: "hades-2",
    title: "Hades II",
    genre: "Roguelite / Acción",
    price: 449,
    originalPrice: null,
    rating: 4.8,
    reviews: 21500,
    image: "🔥",
    gradient: "from-red-600 to-purple-700",
    tag: "NUEVO",
    description: "La secuela del aclamado roguelite. Enfrenta las fuerzas del Tiempo en el inframundo griego.",
    platform: ["PC"],
  },
  {
    id: "starfield",
    title: "Starfield",
    genre: "RPG / Espacial",
    price: 699,
    originalPrice: 999,
    rating: 4.2,
    reviews: 31200,
    image: "🚀",
    gradient: "from-blue-600 to-cyan-700",
    tag: "OFERTA",
    description: "El primer universo nuevo de Bethesda en 25 años. Explora más de 1,000 planetas en el espacio profundo.",
    platform: ["PC", "Xbox"],
  },
  {
    id: "hogwarts-legacy",
    title: "Hogwarts Legacy",
    genre: "Aventura / RPG",
    price: 649,
    originalPrice: 899,
    rating: 4.6,
    reviews: 55700,
    image: "🦉",
    gradient: "from-amber-500 to-yellow-700",
    tag: "OFERTA",
    description: "Vive la experiencia de ser estudiante en Hogwarts en los 1800s. Descubre la magia antigua.",
    platform: ["PC", "PS5", "Xbox"],
  },
];
